// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "234b4e270f524d8ef33014c5c4c8ccde"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"15073accf79f3f91b90312cd588f1849": "1f8b08000000000000ff94924f6bdb4010c5cfda4f31e85024a3aeee011f9ad83439c494a6b752ca489ac88bb57fd819b92d42dfbd48fe839d824b4e2bbdddf7de6fd90958efb025b0689c52c6061f0532955416d2d6c8b6af74ed6dd9fa8fbb88e2b93c2e61d7968ea4dc8a84b2eab0218b2c1453955cfa8c5034ae2db9afb846575adf50f79f33a1eb5be3b864f1115b4a1500403a0c7a8396c671aefc47648a7b53d39b68defac0614e6fa83616bb54e54aed3102c73d2c8e2efd725895923f816018f4b36f1e3a641e4760897d2d30a8a48123925ea15709c1a2b27aed5ae3488d4abdf6ae860dfdca72585c470c2a89247d74f0e16a6318cfbe0cdf987278724656e8b3abda7c0a9bd89770829f2a5137b94a5037b08466fa78366d44a12c57e3cd824791905dde642e404db004ba45371b73a0187d9c2cd3abe8afbe178a19c77d01a8293fdfdb99ee56d897e86b625eff96681c9b3ae34035182705d04983c53c3cfa618bc69d4f16407b72c2f0fdc7e5f6a45dc0bd8f6232cf0405549daf77df8c2516b4e140346b8fc8db69348c6b8f08d77c9352c02b111c074faf0eebbba9ce2f398f6005774b40dde8d57d964ffffa85244b5b1fed9d60d5d14f1fc478c76901e97af3f969b35e3e39e757f769ae3ff5e24f712ac9951ad5df000000ffffd7d9063900040000",
		"199ad9abb6909544028bc5dd60e13162": "1f8b08000000000000ff5cca3b8ec2301000d07ae71453ee16f127d9e07009eee024a3c122f6087f105294bb53d020aad7bc286bdb08f75d5d7ca4e3006041abec0090e9de4226fc0544440ef5da66b548d42cdd2dfb2a45bfc1e84ba5fcdd42a51c12ebd2e6b2f8f4b17e58369f584966fdd4892a3e8c32ca74bdb16773ea273b8dc3ffd8adde0e6e7193b3ab833f8057000000ffffc1665f1aad000000",
		"19cc0e1aa84ea3978bd983e5c849ace9": "1f8b08000000000000ff2a484cce4e4c4f554849cce7e24a2bcd4b5670c9d7d0ace6e2aa05040000ffffd318594c1a000000",
		"1db18360e80cf6aff78b6551ad6ebb67": "1f8b08000000000000ff548c318ec23010456bff538c52ac92d52aeeb7a6a6e1048e33180b625be3310845b93b05a1a0fdffbd579cbfbac05459eed13310979245a987e942d44b9b469f171b9525a6606b9baa77c9965b0b31555b358b0bdc6100f459984eef0e5595e69556989976683cb88c0d38b7e4e9c88ffeeb19e8f7e3ae30c2da24d1cf3ead3066fea7f90f66c38657000000ffff3122ce6bb5000000",
		"53c9328d2bec1463442936e123699a5a": "1f8b08000000000000ff64cd3d6e03211005e09a39c513d5ae95401fc965942e457202964c30daf0236037c58abb47d8561ad33c896fe64d3676358e71692d13f990536998482c01d2f976d9166553d02e3dafc5b454f53df2ea74e4a6c79e5e7ecc1707531b1749421e877a37817bd795cbee2d4b9a8976534671dd2d4ef77ff579cbc1df5bb4f8485be332d5878927304e4b50afd1f9c8338e5bd1199584c3cb19acde4adaf224b5c95ece240e12a20e71ff52ad8983ae06005ae3b7f8c628d7bb50e391109d44a74e7f010000ffffd6794f5e1c010000",
		"7e573a542eb21fa4bbc259a7b00dbcca": "1f8b08000000000000ff2a484cce4e4c4f55c8cd4f49cde1e22aa92c4855a8aed6f3cd4f71ce492c2eaead55282e292a4d2e51a8e6aae502040000ffffcb815bad2d000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("all", "./templates/plugin")
		b.SetResolver("dao/dao.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "19cc0e1aa84ea3978bd983e5c849ace9"})
		b.SetResolver("go.mod.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "199ad9abb6909544028bc5dd60e13162"})
		b.SetResolver("http/http.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "53c9328d2bec1463442936e123699a5a"})
		b.SetResolver("main.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "15073accf79f3f91b90312cd588f1849"})
		b.SetResolver("model/model.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "7e573a542eb21fa4bbc259a7b00dbcca"})
		b.SetResolver("service/service.go.tmpl", packr.Pointer{ForwardBox: gk, ForwardPath: "1db18360e80cf6aff78b6551ad6ebb67"})
	}()

	return nil
}()
