// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/itering/subscan/internal/server/http"
	"github.com/itering/subscan/internal/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	serviceService := service.New()
	engine := http.New(serviceService)
	app, cleanup, err := NewApp(serviceService, engine)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}
