// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package codec_protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExtrinsicRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MetadataVersion      int32    `protobuf:"varint,2,opt,name=metadataVersion,proto3" json:"metadataVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtrinsicRequest) Reset()         { *m = ExtrinsicRequest{} }
func (m *ExtrinsicRequest) String() string { return proto.CompactTextString(m) }
func (*ExtrinsicRequest) ProtoMessage()    {}
func (*ExtrinsicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b75fa9157bf5f75b, []int{0}
}
func (m *ExtrinsicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtrinsicRequest.Unmarshal(m, b)
}
func (m *ExtrinsicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtrinsicRequest.Marshal(b, m, deterministic)
}
func (dst *ExtrinsicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtrinsicRequest.Merge(dst, src)
}
func (m *ExtrinsicRequest) XXX_Size() int {
	return xxx_messageInfo_ExtrinsicRequest.Size(m)
}
func (m *ExtrinsicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtrinsicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExtrinsicRequest proto.InternalMessageInfo

func (m *ExtrinsicRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ExtrinsicRequest) GetMetadataVersion() int32 {
	if m != nil {
		return m.MetadataVersion
	}
	return 0
}

type ExtrinsicReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtrinsicReply) Reset()         { *m = ExtrinsicReply{} }
func (m *ExtrinsicReply) String() string { return proto.CompactTextString(m) }
func (*ExtrinsicReply) ProtoMessage()    {}
func (*ExtrinsicReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b75fa9157bf5f75b, []int{1}
}
func (m *ExtrinsicReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtrinsicReply.Unmarshal(m, b)
}
func (m *ExtrinsicReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtrinsicReply.Marshal(b, m, deterministic)
}
func (dst *ExtrinsicReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtrinsicReply.Merge(dst, src)
}
func (m *ExtrinsicReply) XXX_Size() int {
	return xxx_messageInfo_ExtrinsicReply.Size(m)
}
func (m *ExtrinsicReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtrinsicReply.DiscardUnknown(m)
}

var xxx_messageInfo_ExtrinsicReply proto.InternalMessageInfo

func (m *ExtrinsicReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EventRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MetadataVersion      int32    `protobuf:"varint,2,opt,name=metadataVersion,proto3" json:"metadataVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b75fa9157bf5f75b, []int{2}
}
func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (dst *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(dst, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EventRequest) GetMetadataVersion() int32 {
	if m != nil {
		return m.MetadataVersion
	}
	return 0
}

type EventReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventReply) Reset()         { *m = EventReply{} }
func (m *EventReply) String() string { return proto.CompactTextString(m) }
func (*EventReply) ProtoMessage()    {}
func (*EventReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b75fa9157bf5f75b, []int{3}
}
func (m *EventReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventReply.Unmarshal(m, b)
}
func (m *EventReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventReply.Marshal(b, m, deterministic)
}
func (dst *EventReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReply.Merge(dst, src)
}
func (m *EventReply) XXX_Size() int {
	return xxx_messageInfo_EventReply.Size(m)
}
func (m *EventReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReply.DiscardUnknown(m)
}

var xxx_messageInfo_EventReply proto.InternalMessageInfo

func (m *EventReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LogRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MetadataVersion      int32    `protobuf:"varint,2,opt,name=metadataVersion,proto3" json:"metadataVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b75fa9157bf5f75b, []int{4}
}
func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (dst *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(dst, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LogRequest) GetMetadataVersion() int32 {
	if m != nil {
		return m.MetadataVersion
	}
	return 0
}

type LogReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogReply) Reset()         { *m = LogReply{} }
func (m *LogReply) String() string { return proto.CompactTextString(m) }
func (*LogReply) ProtoMessage()    {}
func (*LogReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b75fa9157bf5f75b, []int{5}
}
func (m *LogReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogReply.Unmarshal(m, b)
}
func (m *LogReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogReply.Marshal(b, m, deterministic)
}
func (dst *LogReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogReply.Merge(dst, src)
}
func (m *LogReply) XXX_Size() int {
	return xxx_messageInfo_LogReply.Size(m)
}
func (m *LogReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LogReply.DiscardUnknown(m)
}

var xxx_messageInfo_LogReply proto.InternalMessageInfo

func (m *LogReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StorageRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DecoderType          string   `protobuf:"bytes,2,opt,name=decoderType,proto3" json:"decoderType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageRequest) Reset()         { *m = StorageRequest{} }
func (m *StorageRequest) String() string { return proto.CompactTextString(m) }
func (*StorageRequest) ProtoMessage()    {}
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b75fa9157bf5f75b, []int{6}
}
func (m *StorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageRequest.Unmarshal(m, b)
}
func (m *StorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageRequest.Marshal(b, m, deterministic)
}
func (dst *StorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageRequest.Merge(dst, src)
}
func (m *StorageRequest) XXX_Size() int {
	return xxx_messageInfo_StorageRequest.Size(m)
}
func (m *StorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageRequest proto.InternalMessageInfo

func (m *StorageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *StorageRequest) GetDecoderType() string {
	if m != nil {
		return m.DecoderType
	}
	return ""
}

type StorageReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageReply) Reset()         { *m = StorageReply{} }
func (m *StorageReply) String() string { return proto.CompactTextString(m) }
func (*StorageReply) ProtoMessage()    {}
func (*StorageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_b75fa9157bf5f75b, []int{7}
}
func (m *StorageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageReply.Unmarshal(m, b)
}
func (m *StorageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageReply.Marshal(b, m, deterministic)
}
func (dst *StorageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageReply.Merge(dst, src)
}
func (m *StorageReply) XXX_Size() int {
	return xxx_messageInfo_StorageReply.Size(m)
}
func (m *StorageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageReply.DiscardUnknown(m)
}

var xxx_messageInfo_StorageReply proto.InternalMessageInfo

func (m *StorageReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ExtrinsicRequest)(nil), "codec_protos.ExtrinsicRequest")
	proto.RegisterType((*ExtrinsicReply)(nil), "codec_protos.ExtrinsicReply")
	proto.RegisterType((*EventRequest)(nil), "codec_protos.EventRequest")
	proto.RegisterType((*EventReply)(nil), "codec_protos.EventReply")
	proto.RegisterType((*LogRequest)(nil), "codec_protos.LogRequest")
	proto.RegisterType((*LogReply)(nil), "codec_protos.LogReply")
	proto.RegisterType((*StorageRequest)(nil), "codec_protos.StorageRequest")
	proto.RegisterType((*StorageReply)(nil), "codec_protos.StorageReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ToolsClient is the client API for Tools service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToolsClient interface {
	DecodeExtrinsic(ctx context.Context, in *ExtrinsicRequest, opts ...grpc.CallOption) (*ExtrinsicReply, error)
	DecodeEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventReply, error)
	DecodeLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogReply, error)
	DecodeStorage(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*StorageReply, error)
}

type toolsClient struct {
	cc *grpc.ClientConn
}

func NewToolsClient(cc *grpc.ClientConn) ToolsClient {
	return &toolsClient{cc}
}

func (c *toolsClient) DecodeExtrinsic(ctx context.Context, in *ExtrinsicRequest, opts ...grpc.CallOption) (*ExtrinsicReply, error) {
	out := new(ExtrinsicReply)
	err := c.cc.Invoke(ctx, "/codec_protos.Tools/DecodeExtrinsic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsClient) DecodeEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventReply, error) {
	out := new(EventReply)
	err := c.cc.Invoke(ctx, "/codec_protos.Tools/DecodeEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsClient) DecodeLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogReply, error) {
	out := new(LogReply)
	err := c.cc.Invoke(ctx, "/codec_protos.Tools/DecodeLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsClient) DecodeStorage(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*StorageReply, error) {
	out := new(StorageReply)
	err := c.cc.Invoke(ctx, "/codec_protos.Tools/DecodeStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolsServer is the server API for Tools service.
type ToolsServer interface {
	DecodeExtrinsic(context.Context, *ExtrinsicRequest) (*ExtrinsicReply, error)
	DecodeEvent(context.Context, *EventRequest) (*EventReply, error)
	DecodeLog(context.Context, *LogRequest) (*LogReply, error)
	DecodeStorage(context.Context, *StorageRequest) (*StorageReply, error)
}

func RegisterToolsServer(s *grpc.Server, srv ToolsServer) {
	s.RegisterService(&_Tools_serviceDesc, srv)
}

func _Tools_DecodeExtrinsic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtrinsicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).DecodeExtrinsic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codec_protos.Tools/DecodeExtrinsic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).DecodeExtrinsic(ctx, req.(*ExtrinsicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tools_DecodeEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).DecodeEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codec_protos.Tools/DecodeEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).DecodeEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tools_DecodeLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).DecodeLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codec_protos.Tools/DecodeLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).DecodeLog(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tools_DecodeStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).DecodeStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codec_protos.Tools/DecodeStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).DecodeStorage(ctx, req.(*StorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tools_serviceDesc = grpc.ServiceDesc{
	ServiceName: "codec_protos.Tools",
	HandlerType: (*ToolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecodeExtrinsic",
			Handler:    _Tools_DecodeExtrinsic_Handler,
		},
		{
			MethodName: "DecodeEvent",
			Handler:    _Tools_DecodeEvent_Handler,
		},
		{
			MethodName: "DecodeLog",
			Handler:    _Tools_DecodeLog_Handler,
		},
		{
			MethodName: "DecodeStorage",
			Handler:    _Tools_DecodeStorage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_b75fa9157bf5f75b) }

var fileDescriptor_rpc_b75fa9157bf5f75b = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x4f, 0x83, 0x30,
	0x14, 0xc7, 0x65, 0xc9, 0x54, 0xde, 0x70, 0x33, 0x3d, 0x18, 0xd2, 0x18, 0x43, 0x88, 0x31, 0xc4,
	0x03, 0x07, 0xfd, 0x00, 0x5e, 0xe4, 0x24, 0x07, 0xc5, 0x65, 0x57, 0x83, 0xf0, 0x42, 0x48, 0x18,
	0xad, 0x6d, 0x35, 0xf2, 0xa9, 0xfc, 0x8a, 0x66, 0x05, 0x27, 0x36, 0x03, 0x2f, 0x3b, 0xf6, 0xfd,
	0x9b, 0xdf, 0xaf, 0x79, 0xff, 0x82, 0x2d, 0x78, 0x16, 0x72, 0xc1, 0x14, 0x23, 0x4e, 0xc6, 0x72,
	0xcc, 0x5e, 0xf4, 0x41, 0xfa, 0x2b, 0x38, 0x8d, 0x3e, 0x95, 0x28, 0x6b, 0x59, 0x66, 0x09, 0xbe,
	0xbd, 0xa3, 0x54, 0xc4, 0x85, 0xa3, 0x35, 0x4a, 0x99, 0x16, 0xe8, 0x5a, 0x9e, 0x15, 0xd8, 0xc9,
	0xcf, 0x91, 0x04, 0xb0, 0x58, 0xa3, 0x4a, 0xf3, 0x54, 0xa5, 0x2b, 0x14, 0xb2, 0x64, 0xb5, 0x3b,
	0xf1, 0xac, 0x60, 0x9a, 0x98, 0x63, 0xff, 0x1a, 0xe6, 0x3d, 0x2e, 0xaf, 0x9a, 0x61, 0xaa, 0x9f,
	0x80, 0x13, 0x7d, 0x60, 0xad, 0xf6, 0xe9, 0xbf, 0x02, 0xe8, 0x98, 0xe3, 0xee, 0x47, 0x80, 0x98,
	0x15, 0xfb, 0x34, 0x5f, 0xc2, 0xb1, 0x26, 0x8e, 0x7b, 0x63, 0x98, 0x3f, 0x2b, 0x26, 0xd2, 0x02,
	0xff, 0x77, 0x7b, 0x30, 0xcb, 0x71, 0xd3, 0x9a, 0x58, 0x36, 0x1c, 0xb5, 0xd7, 0x4e, 0xfa, 0x23,
	0x3f, 0x00, 0x67, 0x4b, 0x1b, 0xf5, 0xde, 0x7c, 0x4d, 0x60, 0xba, 0x64, 0xac, 0x92, 0xe4, 0x09,
	0x16, 0xf7, 0x1a, 0xb1, 0xed, 0x89, 0x5c, 0x84, 0xfd, 0xbf, 0x11, 0x9a, 0x1f, 0x83, 0x9e, 0x0f,
	0xe6, 0xbc, 0x6a, 0xfc, 0x03, 0x12, 0xc1, 0xac, 0x43, 0x6e, 0x56, 0x4f, 0xa8, 0x71, 0xbd, 0xd7,
	0x31, 0x75, 0x77, 0x66, 0x2d, 0xe6, 0x0e, 0xec, 0x16, 0x13, 0xb3, 0x82, 0x18, 0x17, 0x7f, 0xcb,
	0xa2, 0x67, 0x3b, 0x92, 0x16, 0xf0, 0x00, 0x27, 0x2d, 0xa0, 0x5b, 0x0a, 0x31, 0x1e, 0xfe, 0x77,
	0xf3, 0x94, 0x0e, 0xa4, 0x1a, 0xf6, 0x7a, 0xa8, 0xc7, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xbd, 0x69, 0x8e, 0xd9, 0x43, 0x03, 0x00, 0x00,
}
